id: I14C63073
legacy_id: P008256
ocr_import_info:
  bdrc_scan_id: W00EGS1016950
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T07:43:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:50:21.346086+00:00'
last_modified: 2022-08-29 18:51:49.329091
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016950
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016950
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་གདམས་གསར་མའི་དགེ་བཤེས་འགའ་ཞིག་གི་རྣམ་ཐར་དང་གསུང་ཐོར་བུ་བསྒྲིགས་པ།
  author: ལྡན་མ་སྟོང་དཔོན་ངག་དབང་ཆོས་འགྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.815314121538886
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I01JW201:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW201
      total_pages: 610
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I01JW201.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8313840669989858
    legacy_id: v002
  I01JW200:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW200
      total_pages: 420
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW200.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.7702360205013322
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
