id: I14C63073
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:47:36+00:00'
last_modified: '2022-06-08T08:16:49.492158+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016950
  title: བཀའ་གདམས་གསར་མའི་དགེ་བཤེས་འགའ་ཞིག་གི་རྣམ་ཐར་དང་གསུང་ཐོར་བུ་བསྒྲིགས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4499':
      image_group_id: I01JW200
      title: ''
      total_pages: 420
      order: 1
      base_file: 4499.txt
    ABA5:
      image_group_id: I01JW201
      title: ''
      total_pages: 610
      order: 2
      base_file: ABA5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
